[config]
default_to_workspace = false

[tasks.setup-vm]
script = ["""
  set -euo pipefail
  cargo run -p netsim-vm -- up
  """]

[tasks.target-dir]
script = ['''
  set -euo pipefail
  if [ -n "${RUST_TARGET:-}" ]; then
    target="${RUST_TARGET}"
  else
    target="$(rustc -vV | awk '/^host:/{print $2}')"
  fi
  base="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
  echo "${base}/${target}"
  ''']

[tasks.setcap]
command = "./setcap.sh"

[tasks.run-local]
dependencies = ["setcap"]
command = "cargo"
args = ["run", "--", "run", "${@}"]

[tasks.test-local]
dependencies = ["setcap"]
command = "cargo"
args = ["test", "${@}"]

[tasks.run-vm]
script = ['''
  set -euo pipefail
  TARGET_BASE="$(cargo metadata --format-version 1 --no-deps | jq -r '.target_directory')"
  MUSL_TARGET="x86_64-unknown-linux-musl"
  cargo build --release --target "${MUSL_TARGET}" -p netsim --bin netsim --example transfer
  cargo run -p netsim-vm -- run --netsim-version "path:${TARGET_BASE}/${MUSL_TARGET}/release/netsim" ${@}
  ''']

[tasks.test-vm]
script = ['''
  set -euo pipefail
  cargo run -p netsim-vm -- test --target "x86_64-unknown-linux-musl" ${@}
  ''']

[tasks.vm-status]
script = ['''
  cargo run -p netsim-vm -- status
  ''']

[tasks.vm-down]
script = ['''
  echo "Shutting down QEMU VM..."
  cargo run -p netsim-vm -- down
  ''']

[tasks.start]
dependencies = ["run-vm"]
