[sim]
name = "integration-relay_only-1_to_3"
binaries = "iroh-defaults.toml"

[[router]]
name = "dc"

[device.relay.eth0]
gateway = "dc"

[device.provider.eth0]
gateway = "dc"

[device.fetcher]
count = 3

[device.fetcher.eth0]
gateway = "dc"

[[step]]
action      = "spawn"
id          = "relay"
device      = "relay"
cmd         = ["${binary.relay}", "--dev"]
ready_after = "2s"

[[step]]
action   = "spawn"
kind     = "iroh-transfer"
id       = "xfer"
provider = "provider"
fetchers = ["fetcher-0", "fetcher-1", "fetcher-2"]
strategy = "endpoint_id_with_direct_addrs"
duration = "20s"
relay_url = "http://$NETSIM_IP_relay:3340"
fetch_args = ["--size=1G", "--relay-only"]

[[step]]
action = "wait-for"
id     = "xfer"
