[sim]
name = "iroh-iroh_10gb-1_to_1"
binaries = "iroh-defaults.toml"

[[router]]
name = "dc"

[device.provider.eth0]
gateway = "dc"

[device.fetcher.eth0]
gateway = "dc"

[[step]]
action   = "spawn"
kind     = "iroh-transfer"
id       = "xfer"
provider = "provider"
fetcher  = "fetcher"
strategy = "endpoint_id_with_direct_addrs"
duration = "20s"
fetch_args = ["--size=10G"]

[[step]]
action = "wait-for"
id     = "xfer"
