[sim]
name = "iroh-iroh_10gb-1_to_5"
binaries = "iroh-defaults.toml"

[[router]]
name = "dc"

[device.provider.eth0]
gateway = "dc"

[device.fetcher]
count = 5

[device.fetcher.eth0]
gateway = "dc"

[[step]]
action   = "spawn"
kind     = "iroh-transfer"
id       = "xfer"
provider = "provider"
fetchers = ["fetcher-0", "fetcher-1", "fetcher-2", "fetcher-3", "fetcher-4"]
strategy = "endpoint_id_with_direct_addrs"
duration = "20s"
fetch_args = ["--size=10G"]

[[step]]
action = "wait-for"
id     = "xfer"
