[sim]
name = "ported-iroh-iroh-2_to_2"
binaries = "iroh-defaults.toml"
chuck_compat = true

[[router]]
name = "dc"

[device.provider]
count = 2

[device.provider.eth0]
gateway = "dc"

[device.fetcher]
count = 2

[device.fetcher.eth0]
gateway = "dc"

[[step]]
action   = "spawn"
kind     = "iroh-transfer"
id       = "xfer-0"
provider = "provider-0"
fetcher  = "fetcher-0"
strategy = "endpoint_id_with_direct_addrs"
duration = "20s"
fetch_args = ["--size=1G"]

[[step]]
action   = "spawn"
kind     = "iroh-transfer"
id       = "xfer-1"
provider = "provider-1"
fetcher  = "fetcher-1"
strategy = "endpoint_id_with_direct_addrs"
duration = "20s"
fetch_args = ["--size=1G"]

[[step]]
action = "wait-for"
id     = "xfer-0"

[[step]]
action = "wait-for"
id     = "xfer-1"
