[[extends]]
file = "iroh-defaults.toml"

[sim]
name     = "iroh-switch-direct"
topology = "switch-direct"

[[step]]
use      = "transfer-provider"
id       = "provider"
device   = "provider"
args     = []

[[step]]
use    = "transfer-fetcher"
id     = "fetcher"
device = "fetcher"
args   = ["${provider.endpoint_id}",
          "--remote-direct-address", "${provider.direct_addr}"]

[[step]]
action   = "wait"
duration = "10s"

[[step]]
action = "set-default-route"
device = "fetcher"
to     = "eth0"

[[step]]
action  = "wait-for"
id      = "fetcher"
timeout = "600s"

[[step]]
action = "assert"
checks = [
  "fetcher.conn_type contains Direct",
]
