[[extends]]
file = "iroh-defaults.toml"

[sim]
name     = "iroh-1to1-nat-ping"
topology = "1to1-nat"

[[step]]
use  = "relay-setup"
vars = { device = "relay" }

[[step]]
action = "run"
device = "provider"
cmd    = ["ping", "-c", "3", "-W", "2", "$NETSIM_IP_relay"]

[[step]]
action = "run"
device = "fetcher"
cmd    = ["ping", "-c", "3", "-W", "2", "$NETSIM_IP_relay"]
