name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: taiki-e/install-action@cargo-make
      - uses: taiki-e/install-action@nextest

      - uses: Swatinem/rust-cache@v2

      - name: Check
        run: cargo check --workspace --tests

      - name: Test
        run: cargo nextest run --workspace

      - name: Clippy
        run: cargo clippy --workspace --tests -- -D warnings

      - name: Format
        run: cargo make format-check
